# Generated by Django 4.1.5 on 2023-01-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='medidores.medidor'),
        ),
    ]
